In [34]:
import pandas as pd

In [131]:
weekly_data = pd.read_csv('Resources/offense_weekly_data.csv')
weekly_data.head(20)

,id,name,position,team,season,week,season_type,opponent_team,completions,attempts,...,round,overall,forty,bench,vertical,index,offense_snaps,teams_offense_snaps,offense_pct,years_played
0,1045,A.J. Brown,WR,TEN,2019,1,REG,CLE,0,0,...,2.0,51.0,4.49,19.0,36.5,237.0,25.0,60.0,0.42,1.0
1,1045,A.J. Brown,WR,TEN,2019,2,REG,IND,0,0,...,2.0,51.0,4.49,19.0,36.5,2254.0,27.0,59.0,0.46,1.0
2,1045,A.J. Brown,WR,TEN,2019,3,REG,JAX,0,0,...,2.0,51.0,4.49,19.0,36.5,2920.0,39.0,80.0,0.49,1.0
3,1045,A.J. Brown,WR,TEN,2019,4,REG,ATL,0,0,...,2.0,51.0,4.49,19.0,36.5,4433.0,26.0,62.0,0.42,1.0
4,1045,A.J. Brown,WR,TEN,2019,5,REG,BUF,0,0,...,2.0,51.0,4.49,19.0,36.5,6346.0,37.0,58.0,0.64,1.0
5,1045,A.J. Brown,WR,TEN,2019,6,REG,DEN,0,0,...,2.0,51.0,4.49,19.0,36.5,7292.0,38.0,66.0,0.58,1.0
6,1045,A.J. Brown,WR,TEN,2019,7,REG,LAC,0,0,...,2.0,51.0,4.49,19.0,36.5,9120.0,39.0,62.0,0.63,1.0
7,1045,A.J. Brown,WR,TEN,2019,8,REG,TB,0,0,...,2.0,51.0,4.49,19.0,36.5,10458.0,36.0,60.0,0.61,1.0
8,1045,A.J. Brown,WR,TEN,2019,9,REG,CAR,0,0,...,2.0,51.0,4.49,19.0,36.5,11037.0,50.0,73.0,0.69,1.0
9,1045,A.J. Brown,WR,TEN,2019,10,REG,KC,0,0,...,2.0,51.0,4.49,19.0,36.5,12859.0,47.0,50.0,0.94,1.0
10,1045,A.J. Brown,WR,TEN,2019,12,REG,JAX,0,0,...,2.0,51.0,4.49,19.0,36.5,15289.0,37.0,53.0,0.70,1.0
11,1045,A.J. Brown,WR,TEN,2019,13,REG,IND,0,0,...,2.0,51.0,4.49,19.0,36.5,16226.0,53.0,59.0,0.90,1.0
12,1045,A.J. Brown,WR,TEN,2019,14,REG,LV,0,0,...,2.0,51.0,4.49,19.0,36.5,18291.0,51.0,61.0,0.84,1.0
13,1045,A.J. Brown,WR,TEN,2019,15,REG,HOU,0,0,...,2.0,51.0,4.49,19.0,36.5,19412.0,62.0,69.0,0.91,1.0
14,1045,A.J. Brown,WR,TEN,2019,16,REG,NO,0,0,...,2.0,51.0,4.49,19.0,36.5,20936.0,62.0,62.0,1.00,1.0
15,1045,A.J. Brown,WR,TEN,2019,17,REG,HOU,0,0,...,2.0,51.0,4.49,19.0,36.5,22056.0,49.0,63.0,0.79,1.0
16,1045,A.J. Brown,WR,TEN,2020,1,REG,DEN,0,0,...,2.0,51.0,4.49,19.0,36.5,1346.0,66.0,82.0,0.81,2.0
17,1045,A.J. Brown,WR,TEN,2020,5,REG,BUF,0,0,...,2.0,51.0,4.49,19.0,36.5,7054.0,47.0,67.0,0.71,2.0
18,1045,A.J. Brown,WR,TEN,2020,6,REG,HOU,0,0,...,2.0,51.0,4.49,19.0,36.5,7793.0,63.0,75.0,0.84,2.0
19,1045,A.J. Brown,WR,TEN,2020,7,REG,PIT,0,0,...,2.0,51.0,4.49,19.0,36.5,9296.0,53.0,57.0,0.93,2.0

In [55]:
weekly_data.columns

Index(['id', 'name', 'position', 'team', 'season', 'week', 'season_type',
       'opponent_team', 'completions', 'attempts', 'passing_yards',
       'passing_tds', 'interceptions', 'sacks', 'sack_yards', 'sack_fumbles',
       'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch',
       'passing_first_downs', 'passing_2pt_conversions', 'carries',
       'rushing_yards', 'rushing_tds', 'rushing_fumbles',
       'rushing_fumbles_lost', 'rushing_first_downs',
       'rushing_2pt_conversions', 'receptions', 'targets', 'receiving_yards',
       'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost',
       'receiving_air_yards', 'receiving_yards_after_catch',
       'receiving_first_downs', 'receiving_2pt_conversions', 'target_share',
       'air_yards_share', 'fantasy_points', 'fantasy_points_ppr',
       'total_yards', 'ypa', 'ypc', 'ypr', 'touches', 'count',
       'comp_percentage', 'pass_td_percentage', 'int_percentage',
       'rush_td_percentage', 'rec_td_percentage', 'total_tds', 'td_percentage',
       'passer_rating', 'rookie_season', 'college', 'weight', 'birth_date',
       'rookie_age', 'height_cm', 'height_ft', 'round', 'overall', 'forty',
       'bench', 'vertical', 'index', 'offense_snaps', 'teams_offense_snaps',
       'offense_pct', 'years_played'],
      dtype='object')

In [56]:
# Keeping features wanted to train model
weekly_data = weekly_data[['name','position', 'season', 'week', 'targets', 'ypr', 'receiving_fumbles',
                           'target_share', 'air_yards_share', 'carries',
                           'rush_td_percentage', 'rushing_fumbles', 'attempts', 'comp_percentage', 
                           'passing_2pt_conversions', 'td_percentage', 'sacks',
                           'sack_fumbles', 'offense_snaps', 'teams_offense_snaps', 'round',
                           'overall','fantasy_points_ppr']]

weekly_data

,name,position,season,week,targets,ypr,receiving_fumbles,target_share,air_yards_share,carries,...,comp_percentage,passing_2pt_conversions,td_percentage,sacks,sack_fumbles,offense_snaps,teams_offense_snaps,round,overall,fantasy_points_ppr
0,A.J. Brown,WR,2019,1,4,33.33,0.0,0.17,0.37,0,...,0.0,0,0.00,0.0,0,25.0,60.0,2.0,51.0,13.0
1,A.J. Brown,WR,2019,2,5,8.33,0.0,0.19,0.17,0,...,0.0,0,0.00,0.0,0,27.0,59.0,2.0,51.0,5.5
2,A.J. Brown,WR,2019,3,5,4.00,0.0,0.13,0.16,0,...,0.0,0,0.00,0.0,0,39.0,80.0,2.0,51.0,1.4
3,A.J. Brown,WR,2019,4,3,31.33,0.0,0.14,0.33,0,...,0.0,0,0.67,0.0,0,26.0,62.0,2.0,51.0,24.4
4,A.J. Brown,WR,2019,5,2,13.50,0.0,0.10,0.24,0,...,0.0,0,0.00,0.0,0,37.0,58.0,2.0,51.0,4.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55009,Zurlon Tipton,RB,2014,17,2,22.50,0.0,0.06,0.00,9,...,0.0,0,0.00,0.0,0,28.0,67.0,0.0,0.0,8.6
55010,Zurlon Tipton,RB,2015,5,1,0.00,0.0,0.03,-0.00,2,...,0.0,0,0.00,0.0,0,9.0,65.0,0.0,0.0,0.9
55011,Zurlon Tipton,RB,2015,13,2,7.00,0.0,0.06,0.00,1,...,0.0,0,0.00,0.0,0,11.0,58.0,0.0,0.0,1.7
55012,Zurlon Tipton,RB,2015,14,5,12.50,0.0,0.12,0.08,1,...,0.0,0,0.00,0.0,0,14.0,74.0,0.0,0.0,9.7
55013,Zurlon Tipton,RB,2015,15,0,0.00,0.0,0.00,0.00,1,...,0.0,0,0.00,0.0,0,5.0,56.0,0.0,0.0,0.4

In [57]:
# Creating a lookup table to find players that played last season
lookup_table_2023_weekly = weekly_data[weekly_data['season'] == 2023]
lookup_table_2023_weekly

,name,position,season,week,targets,ypr,receiving_fumbles,target_share,air_yards_share,carries,...,comp_percentage,passing_2pt_conversions,td_percentage,sacks,sack_fumbles,offense_snaps,teams_offense_snaps,round,overall,fantasy_points_ppr
60,A.J. Brown,WR,2023,1,10,11.29,0.0,0.33,0.59,0,...,0.0,0,0.00,0.0,0,60.0,66.0,2.0,51.0,14.9
61,A.J. Brown,WR,2023,2,6,7.25,0.0,0.27,0.27,0,...,0.0,0,0.00,0.0,0,74.0,78.0,2.0,51.0,6.9
62,A.J. Brown,WR,2023,3,14,14.56,0.0,0.40,0.39,0,...,0.0,0,0.00,0.0,0,66.0,81.0,2.0,51.0,22.1
63,A.J. Brown,WR,2023,4,13,19.44,0.0,0.38,0.58,0,...,0.0,0,0.22,0.0,0,68.0,71.0,2.0,51.0,38.5
64,A.J. Brown,WR,2023,5,8,21.17,0.0,0.24,0.51,0,...,0.0,0,0.00,0.0,0,78.0,79.0,2.0,51.0,18.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54996,Zay Jones,WR,2023,14,14,5.80,0.0,0.29,0.47,0,...,0.0,0,0.00,0.0,0,64.0,77.0,2.0,37.0,7.9
54997,Zay Jones,WR,2023,15,8,11.80,0.0,0.19,0.33,0,...,0.0,0,0.00,0.0,0,38.0,63.0,2.0,37.0,10.9
54998,Zay Jones,WR,2023,18,9,7.83,0.0,0.22,0.23,0,...,0.0,0,0.00,0.0,0,66.0,71.0,2.0,37.0,10.7
55006,Zonovan Knight,RB,2023,3,0,0.00,0.0,0.00,0.00,3,...,0.0,0,0.00,0.0,0,7.0,70.0,NaN,NaN,1.3
55007,Zonovan Knight,RB,2023,5,1,8.00,0.0,0.04,-0.03,0,...,0.0,0,0.00,0.0,0,2.0,67.0,NaN,NaN,1.8

In [86]:
# Merging the lookup table with all_data to get each players total carrer stats ONLY IF they played last season
current_players_weekly_df = weekly_data.merge(lookup_table_2023_weekly, on=['name', 'week'], how='left', suffixes=('', '_y'))

# Dropping the dupe columns after the merge
current_players_weekly_df = current_players_weekly_df.drop(['position_y', 'season_y', 'targets_y', 'ypr_y',
                                                           'receiving_fumbles_y', 'target_share_y', 'air_yards_share_y',
                                                           'carries_y', 'rush_td_percentage_y', 'rushing_fumbles_y', 'attempts_y',
                                                           'comp_percentage_y', 'passing_2pt_conversions_y', 'td_percentage_y',
                                                           'sacks_y', 'sack_fumbles_y', 'offense_snaps_y', 'teams_offense_snaps_y',
                                                           'round_y', 'overall_y', 'fantasy_points_ppr_y'], axis = 1)

current_players_weekly_df

,name,position,season,week,targets,ypr,receiving_fumbles,target_share,air_yards_share,carries,...,comp_percentage,passing_2pt_conversions,td_percentage,sacks,sack_fumbles,offense_snaps,teams_offense_snaps,round,overall,fantasy_points_ppr
0,A.J. Brown,WR,2019,1,4,33.33,0.0,0.17,0.37,0,...,0.0,0,0.00,0.0,0,25.0,60.0,2.0,51.0,13.0
1,A.J. Brown,WR,2019,2,5,8.33,0.0,0.19,0.17,0,...,0.0,0,0.00,0.0,0,27.0,59.0,2.0,51.0,5.5
2,A.J. Brown,WR,2019,3,5,4.00,0.0,0.13,0.16,0,...,0.0,0,0.00,0.0,0,39.0,80.0,2.0,51.0,1.4
3,A.J. Brown,WR,2019,4,3,31.33,0.0,0.14,0.33,0,...,0.0,0,0.67,0.0,0,26.0,62.0,2.0,51.0,24.4
4,A.J. Brown,WR,2019,5,2,13.50,0.0,0.10,0.24,0,...,0.0,0,0.00,0.0,0,37.0,58.0,2.0,51.0,4.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55009,Zurlon Tipton,RB,2014,17,2,22.50,0.0,0.06,0.00,9,...,0.0,0,0.00,0.0,0,28.0,67.0,0.0,0.0,8.6
55010,Zurlon Tipton,RB,2015,5,1,0.00,0.0,0.03,-0.00,2,...,0.0,0,0.00,0.0,0,9.0,65.0,0.0,0.0,0.9
55011,Zurlon Tipton,RB,2015,13,2,7.00,0.0,0.06,0.00,1,...,0.0,0,0.00,0.0,0,11.0,58.0,0.0,0.0,1.7
55012,Zurlon Tipton,RB,2015,14,5,12.50,0.0,0.12,0.08,1,...,0.0,0,0.00,0.0,0,14.0,74.0,0.0,0.0,9.7
55013,Zurlon Tipton,RB,2015,15,0,0.00,0.0,0.00,0.00,1,...,0.0,0,0.00,0.0,0,5.0,56.0,0.0,0.0,0.4

In [87]:
current_players_weekly_df.columns

Index(['name', 'position', 'season', 'week', 'targets', 'ypr',
       'receiving_fumbles', 'target_share', 'air_yards_share', 'carries',
       'rush_td_percentage', 'rushing_fumbles', 'attempts', 'comp_percentage',
       'passing_2pt_conversions', 'td_percentage', 'sacks', 'sack_fumbles',
       'offense_snaps', 'teams_offense_snaps', 'round', 'overall',
       'fantasy_points_ppr'],
      dtype='object')

In [128]:
# Dropping fantasy_points_ppr from predicting data
lookup_table_2023_weekly_cleaned = lookup_table_2023_weekly.drop(['fantasy_points_ppr', 'season'], axis=1)
lookup_table_2023_weekly_cleaned

,name,position,week,targets,ypr,receiving_fumbles,target_share,air_yards_share,carries,rush_td_percentage,...,attempts,comp_percentage,passing_2pt_conversions,td_percentage,sacks,sack_fumbles,offense_snaps,teams_offense_snaps,round,overall
60,A.J. Brown,WR,1,10,11.29,0.0,0.33,0.59,0,0.0,...,0,0.0,0,0.00,0.0,0,60.0,66.0,2.0,51.0
61,A.J. Brown,WR,2,6,7.25,0.0,0.27,0.27,0,0.0,...,0,0.0,0,0.00,0.0,0,74.0,78.0,2.0,51.0
62,A.J. Brown,WR,3,14,14.56,0.0,0.40,0.39,0,0.0,...,0,0.0,0,0.00,0.0,0,66.0,81.0,2.0,51.0
63,A.J. Brown,WR,4,13,19.44,0.0,0.38,0.58,0,0.0,...,0,0.0,0,0.22,0.0,0,68.0,71.0,2.0,51.0
64,A.J. Brown,WR,5,8,21.17,0.0,0.24,0.51,0,0.0,...,0,0.0,0,0.00,0.0,0,78.0,79.0,2.0,51.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54996,Zay Jones,WR,14,14,5.80,0.0,0.29,0.47,0,0.0,...,0,0.0,0,0.00,0.0,0,64.0,77.0,2.0,37.0
54997,Zay Jones,WR,15,8,11.80,0.0,0.19,0.33,0,0.0,...,0,0.0,0,0.00,0.0,0,38.0,63.0,2.0,37.0
54998,Zay Jones,WR,18,9,7.83,0.0,0.22,0.23,0,0.0,...,0,0.0,0,0.00,0.0,0,66.0,71.0,2.0,37.0
55006,Zonovan Knight,RB,3,0,0.00,0.0,0.00,0.00,3,0.0,...,0,0.0,0,0.00,0.0,0,7.0,70.0,NaN,NaN
55007,Zonovan Knight,RB,5,1,8.00,0.0,0.04,-0.03,0,0.0,...,0,0.0,0,0.00,0.0,0,2.0,67.0,NaN,NaN

In [122]:
lookup_table_2023_weekly_cleaned.columns

Index(['name', 'position', 'week', 'targets', 'ypr', 'receiving_fumbles',
       'target_share', 'air_yards_share', 'carries', 'rush_td_percentage',
       'rushing_fumbles', 'attempts', 'comp_percentage',
       'passing_2pt_conversions', 'td_percentage', 'sacks', 'sack_fumbles',
       'offense_snaps', 'teams_offense_snaps', 'round', 'overall'],
      dtype='object')

In [123]:
# Creating temporary DF to get data for all players careers to calulate average career stats for predicting 
all_years_df = current_players_weekly_df
all_years_df = all_years_df.drop(['fantasy_points_ppr'], axis=1)

all_years_df.head()

,name,position,season,week,targets,ypr,receiving_fumbles,target_share,air_yards_share,carries,...,attempts,comp_percentage,passing_2pt_conversions,td_percentage,sacks,sack_fumbles,offense_snaps,teams_offense_snaps,round,overall
0,A.J. Brown,WR,2019,1,4,33.33,0.0,0.17,0.37,0,...,0,0.0,0,0.00,0.0,0,25.0,60.0,2.0,51.0
1,A.J. Brown,WR,2019,2,5,8.33,0.0,0.19,0.17,0,...,0,0.0,0,0.00,0.0,0,27.0,59.0,2.0,51.0
2,A.J. Brown,WR,2019,3,5,4.00,0.0,0.13,0.16,0,...,0,0.0,0,0.00,0.0,0,39.0,80.0,2.0,51.0
3,A.J. Brown,WR,2019,4,3,31.33,0.0,0.14,0.33,0,...,0,0.0,0,0.67,0.0,0,26.0,62.0,2.0,51.0
4,A.J. Brown,WR,2019,5,2,13.50,0.0,0.10,0.24,0,...,0,0.0,0,0.00,0.0,0,37.0,58.0,2.0,51.0

In [124]:
# Group by player name and calculate career averages
career_averages_weekly = all_years_df.groupby('name')[['targets', 'ypr',
                                               'receiving_fumbles', 'target_share', 'air_yards_share', 'carries',
                                               'rush_td_percentage', 'rushing_fumbles', 'attempts', 'comp_percentage',
                                               'passing_2pt_conversions', 'td_percentage', 'sacks', 'sack_fumbles',
                                               'offense_snaps', 'teams_offense_snaps']]\
                                                        .agg(['mean']).reset_index()

# Reordering column names
career_averages_weekly.columns = ['name', 'targets', 'ypr',
                            'receiving_fumbles', 'target_share', 'air_yards_share', 'carries',
                            'rush_td_percentage', 'rushing_fumbles', 'attempts', 'comp_percentage',
                            'passing_2pt_conversions', 'td_percentage', 'sacks', 'sack_fumbles',
                            'offense_snaps', 'teams_offense_snaps']


career_averages_weekly.head()

,name,targets,ypr,receiving_fumbles,target_share,air_yards_share,carries,rush_td_percentage,rushing_fumbles,attempts,comp_percentage,passing_2pt_conversions,td_percentage,sacks,sack_fumbles,offense_snaps,teams_offense_snaps
0,A.J. Brown,7.766234,15.600909,0.090909,0.267662,0.382857,0.064935,0.012987,0.000000,0.025974,0.0,0.0,0.111948,0.0,0.0,52.792208,67.025974
1,A.J. Derby,3.250000,9.624000,0.100000,0.093500,0.094500,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.087500,0.0,0.0,30.100000,66.700000
2,A.J. Dillon,1.896552,6.016207,0.034483,0.057069,0.002241,10.293103,0.022414,0.017241,0.000000,0.0,0.0,0.021379,0.0,0.0,NaN,NaN
3,A.J. Green,7.975806,12.908306,0.064516,0.238306,0.370403,0.016129,0.000000,0.008065,0.000000,0.0,0.0,0.079516,0.0,0.0,54.322581,67.475806
4,A.J. Jenkins,2.285714,8.987857,0.000000,0.072857,0.117857,0.285714,0.000000,0.071429,0.000000,0.0,0.0,0.000000,0.0,0.0,25.214286,68.428571

In [118]:
# Merging non related numerical and categorical data back with each players career averages
career_averages_weekly_df = career_averages_weekly.merge(lookup_table_2023_weekly_cleaned, on = 'name', how = 'left', suffixes=('', '_y'))

# Dropping unaveraged data
career_averages_weekly_df = career_averages_weekly_df.drop(['week', 'targets_y', 'ypr_y',
                                                           'receiving_fumbles_y', 'target_share_y', 'air_yards_share_y',
                                                           'carries_y', 'rush_td_percentage_y', 'rushing_fumbles_y', 'attempts_y',
                                                           'comp_percentage_y', 'passing_2pt_conversions_y', 'td_percentage_y',
                                                           'sacks_y', 'sack_fumbles_y', 'offense_snaps_y', 'teams_offense_snaps_y'], axis = 1)

# Reordering the position of the columns
career_averages_weekly_df = career_averages_weekly_df[['name', 'targets', 'ypr',
                            'receiving_fumbles', 'target_share', 'air_yards_share', 'carries',
                            'rush_td_percentage', 'rushing_fumbles', 'attempts', 'comp_percentage',
                            'passing_2pt_conversions', 'td_percentage', 'sacks', 'sack_fumbles',
                            'offense_snaps', 'teams_offense_snaps', 'round', 'overall']]
# Dropping all dupes
career_averages_weekly_df.drop_duplicates(inplace=True)
career_averages_weekly_df

,name,targets,ypr,receiving_fumbles,target_share,air_yards_share,carries,rush_td_percentage,rushing_fumbles,attempts,comp_percentage,passing_2pt_conversions,td_percentage,sacks,sack_fumbles,offense_snaps,teams_offense_snaps,round,overall
0,A.J. Brown,7.766234,15.600909,0.090909,0.267662,0.382857,0.064935,0.012987,0.000000,0.025974,0.000000,0.0,0.111948,0.0,0.0,52.792208,67.025974,2.0,51.0
17,A.J. Derby,3.250000,9.624000,0.100000,0.093500,0.094500,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.087500,0.0,0.0,30.100000,66.700000,NaN,NaN
18,A.J. Dillon,1.896552,6.016207,0.034483,0.057069,0.002241,10.293103,0.022414,0.017241,0.000000,0.000000,0.0,0.021379,0.0,0.0,NaN,NaN,NaN,NaN
33,A.J. Green,7.975806,12.908306,0.064516,0.238306,0.370403,0.016129,0.000000,0.008065,0.000000,0.000000,0.0,0.079516,0.0,0.0,54.322581,67.475806,NaN,NaN
34,A.J. Jenkins,2.285714,8.987857,0.000000,0.072857,0.117857,0.285714,0.000000,0.071429,0.000000,0.000000,0.0,0.000000,0.0,0.0,25.214286,68.428571,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6488,Zander Horvath,1.000000,0.625000,0.000000,0.025000,0.003750,0.500000,0.000000,0.000000,0.000000,0.000000,0.0,0.166250,0.0,0.0,9.250000,70.625000,NaN,NaN
6489,Zay Flowers,6.750000,12.473750,0.000000,0.238750,0.238125,0.500000,0.062500,0.000000,0.000000,0.000000,0.0,0.067500,0.0,0.0,56.562500,67.562500,1.0,22.0
6505,Zay Jones,5.221053,10.429474,0.021053,0.158000,0.217474,0.084211,0.000000,0.000000,0.021053,0.010526,0.0,0.049684,0.0,0.0,48.552941,68.611765,2.0,37.0
6514,Zonovan Knight,1.666667,5.714444,0.111111,0.043333,-0.011111,9.777778,0.006667,0.111111,0.000000,0.000000,0.0,0.005556,0.0,0.0,23.000000,68.000000,NaN,NaN
6516,Zurlon Tipton,2.333333,7.958333,0.000000,0.060000,0.010000,2.500000,0.000000,0.000000,0.000000,0.000000,0.0,0.033333,0.0,0.0,14.000000,63.833333,NaN,NaN

In [107]:
career_averages_weekly_df.columns

Index(['name', 'targets', 'ypr', 'receiving_fumbles', 'target_share',
       'air_yards_share', 'carries', 'rush_td_percentage', 'rushing_fumbles',
       'attempts', 'comp_percentage', 'passing_2pt_conversions',
       'td_percentage', 'sacks', 'sack_fumbles', 'offense_snaps',
       'teams_offense_snaps', 'position', 'week', 'targets_y', 'ypr_y',
       'receiving_fumbles_y', 'target_share_y', 'air_yards_share_y',
       'carries_y', 'rush_td_percentage_y', 'rushing_fumbles_y', 'attempts_y',
       'comp_percentage_y', 'passing_2pt_conversions_y', 'td_percentage_y',
       'sacks_y', 'sack_fumbles_y', 'offense_snaps_y', 'teams_offense_snaps_y',
       'round', 'overall'],
      dtype='object')

In [22]:
current_players_df.to_csv('../training_data_per_week.csv', index=False)

In [20]:
lookup_table_2023.to_csv('../2023_player_stats_per_week.csv', index=False)

In [ ]:
career_averages_df.to_csv('../predicting_data.csv', index=False)